### PR TITLE
fix: it is guaranteed that settings.new(Notes|Files)Location exist

### PR DESCRIPTION
**Pull request by ekalinin**
- add `utils/fsUtils` module with `createFolder`;
- use `createFolder` in `handleFiles/handleMessage` to be sure that root folder exists;
- clear some trailing spaces.

Fix for #77

### CODE REVIEW

**Comment by burtasov** [comment]
Hi @ekalinin,

Thanks again for contributing! Did you have some errors related to uncreated folders? Function "this.app.vault.create..." creates folders if they are not exists. Could you, please, describe problem in details, because I didn't get it.

Best Regards, soberHacker

**Comment by soberhacker** [comment]
Hi @ekalinin,

Thanks again for contributing! Did you have some errors related to uncreated folders? Function "this.app.vault.create..." creates folders if they are not exists. Could you, please, describe problem in details, because I didn't get it.

Best Regards, soberHacker

**Comment by ekalinin** [comment]
Hi!

> Did you have some errors related to uncreated folders?

Yeah, when I installed the plugin for the first time, it did not work immediately, since the directory for notes was not created by me earlier.

And there was the following error in the Developer Console:

```
Uncaught (in promise) Error: ENOENT: no such file or directory, open '/Users/xxx/Projects/obsidian/yyy/from-tgx/Xxx - 20230505204503781.md'
```

NB:

Other plugins (like [excalidraw](https://github.com/zsviczian/obsidian-excalidraw-plugin) or [ReadItLater](https://github.com/DominikPieper/obsidian-ReadItLater)) create directories for notes by themselves.

**Comment by soberhacker** [comment]
Understood. Ok. Thanks for explanation!

**Comment by soberhacker** [comment]
https://github.com/soberhacker/obsidian-telegram-sync/releases/tag/1.2.0
- add possibility to run plugin on a few desktops
- add displaying errors
- add forwardFrom to template parsing
- access allowed only for selected telegram users
- improve bot shutdown behavior when plugin is disabled and enabled again
- fix bug with non existed folder
- improve message deletion
- fix template variables names (context -> content)

**Pull request merged**
