### PR TITLE
feat: add enableNotifications setting

### PR DESCRIPTION
**Pull request by ekalinin**
- add `enableNotifications` setting;
- add `TelegramSyncPlugin.displayMessage` to show a popup or write a console message;
- add loading message into `TelegramSyncPlugin.onload` method (like in other plugins)
- clear some trailing spaces.

### CODE REVIEW

**Comment by burtasov** [comment]
Hi @ekalinin,

Good Job! I like your idea of displaying important messages for users, but I don't like idea to add new setting for it. So I suggest to always display errors. In our case, everything is good for displaying, excepting the message text ``` 
this.displayMessage(`Got a message from Telegram Bot: ${msg.text}`)) 
```.
Also all merge requests have to be into "develop" branch. 
Thank you a lot for taking a part of developing this plugin.

Best Regards, Vova

**Comment by soberhacker** [comment]
Hi @ekalinin,

Good Job! I like your idea of displaying important messages for users, but I don't like idea to add new setting for it. So I suggest to always display errors. In our case, everything is good for displaying, excepting the message text ```
this.displayMessage(Got a message from Telegram Bot: ${msg.text}))
```
Also all merge requests have to be into "develop" branch. 

Thank you a lot for taking a part of developing this plugin.

Best Regards, soberHacker

**Comment by ekalinin** [comment]
Hi, 

> I like your idea of displaying important messages for users, but I don't like idea to add new setting for it. So I suggest to always display errors.

Ok, will remove code related to settings.

> excepting the message text "this.displayMessage(Got a message from Telegram Bot: ${msg.text}))"

What do you suggest? Remove it? Or just send it in the console? 

> Also all merge requests have to be into "develop" branch.

Got it. Fixed.

**Comment by soberhacker** [comment]
> Ok, will delete the code related to the settings.
Cool. Thanks

> What do you suggest? Remove it? Or just send it in the console?
Send it in the console.

**Comment by ekalinin** [comment]
> > Ok, will delete the code related to the settings.
> 
> Cool. Thanks
> 
> > What do you suggest? Remove it? Or just send it in the console?
> 
> Send it in the console.

Done. Please, take a look.

**Comment by soberhacker** [comment]
https://github.com/soberhacker/obsidian-telegram-sync/releases/tag/1.2.0
- add possibility to run plugin on a few desktops
- add displaying errors
- add forwardFrom to template parsing
- access allowed only for selected telegram users
- improve bot shutdown behavior when plugin is disabled and enabled again
- fix bug with non existed folder
- improve message deletion
- fix template variables names (context -> content)

**Pull request merged**
